language: python
python:
  - 3.8

branches:
  only:
    - master

before_install:
    - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file envs.yml
    - source activate test-environment

script:
  - PYTHONPATH=:$PYTHONPATH python -m unittest -v test/test.py

